server:
  ip_address: "0.0.0.0"
  port: "8089"
  saved_data_path: "result"
parameter:
  embeddings_name: "sentence-transformers/all-MiniLM-L6-v2"

  DATA_PATH: "data/"
  DB_FAISS_PATH: "ChatBot_Extract_Intent/vectorstore/db_faiss"
  DB_MESSAGES: "ChatBot_Extract_Intent/db_messages/"

  # Số đoạn sẽ được thêm vào lời nhắc. Quá nhiều đoạn trích và bạn có nguy cơ bị cả lời nhắc vượt qua
  # giới hạn mã thông báo và mô hình không thể tìm thấy câu trả lời chính xác
  prompt_number_snippets: 3

  # GPT related constants
  gpt_model_to_use: "gpt-3.5-turbo-16k"

  temperature: 0
  gpt_max_tokens: 256

  # Số tin nhắn của người dùng trước đây sẽ được sử dụng để tìm kiếm các đoạn có liên quan
  search_number_messages: 3

  # PDF Chunking constants
  chunk_size: 256
  chunk_overlap: 50

  # Số đoạn trích được FAISS truy xuất
  number_snippets_to_retrieve: 3
  #Thông tin sản phẩm
  data_private: ./ChatBot_Extract_Intent/data/product_final_204_oke.xlsx

  num_product: 3  # Số lượng sản phẩm tối đa cần tìm


  #
  raw_answer: ["Mình là trợ lý AI của VCC. Mình được tạo ra để hỗ trợ và giải đáp về các sản phẩm của VCC, hiện tại mình vẫn đang trong quá trình phát triển nên không phải lúc nào cũng đúng. Bạn có thể phản hồi để giúp mình cải thiện tốt hơn.",
                "Mình là trợ lý AI của VCC. Mình được tạo ra để hỗ trợ và giải đáp về các sản phẩm của VCC như: Thông tin sản phẩm, giá tiền, số lượng, thông số sản phẩm, . . . Hãy hỏi mĩnh những thông tin này để mình giúp đỡ."]
  
  can_not_res: ['Rất tiếc về điều này. Tôi vẫn đang trong quá trình học và cải thiện, nên không thể giúp bạn với câu hỏi này vào lúc này. Hãy đặt câu hỏi khác để tôi có thể hỗ trợ bạn tốt hơn!',
                'Xin lỗi về sự bất tiện này. Tôi đang cố gắng nâng cao khả năng của mình mỗi ngày, nhưng hiện tại vẫn chưa đủ để xử lý câu hỏi này. Mong bạn thông cảm và tiếp tục hỏi câu hỏi khác nếu cần!',
                'Xin lỗi về sự phiền toái này. Tôi đang trong quá trình học hỏi và cải thiện từng ngày, nhưng vẫn chưa đủ để giải quyết câu hỏi của bạn. Hãy để tôi biết nếu có bất kỳ điều gì khác mà bạn cần giúp đỡ!',
                'Xin lỗi về sự bất tiện này. Hiện tại, tôi vẫn đang trong quá trình học và cải thiện, nên chưa thể giúp bạn với câu hỏi này. Tuy nhiên, tôi rất sẵn lòng hỗ trợ bạn với bất kỳ câu hỏi nào khác bạn có. Hãy đặt câu hỏi khác để tôi có thể giúp bạn tốt hơn!',
                'Xin lỗi, hiện tại tôi vẫn đang trong quá trình học và cải thiện, nên chưa thể giúp bạn với câu hỏi này. Tuy nhiên, tôi rất sẵn lòng hỗ trợ bạn với bất kỳ câu hỏi nào khác bạn có. Hãy đặt câu hỏi khác để tôi có thể giúp bạn tốt hơn!']

  rasa_bottom: [
                {
                "payload": "/Tôi đang quan tâm Máy Giặt Aqua là lồng ngang hay lồng đứng?",
                "title": "Bạn đang quan tâm Máy Giặt Aqua là lồng ngang hay lồng đứng?"
                },
                {
                "payload": "/Tôi muốn mua sản phẩm Đèn năng mặt trời với giá bình dân?",
                "title": " Bạn muốn mua sản phẩm Đèn năng mặt trời với giá bình dân?"
                },
                {
                "payload": "/Tôi muốn biết VCC bán những gì?",
                "title": "Bạn muốn biết VCC bán những gì?"
                },
                {
                "payload": "/Bạn đang quan tâm đến dịch vụ, chính sách của VCC?",
                "title": "Bạn đang quan tâm đến dịch vụ, chính sách của VCC?"
                }]


  example_input: [
    {
            "input_text":"Bann dnagg có boa nhieu sp đêu hòa cao caap",
            "command":"Bạn đang có bao nhiêu sản phẩm điều hòa cao cấp ",
            "object": ["điều hòa"],
            "power":"",           
            "value":"",
            "weight":"",
            "volume":"",
            "intent":"cao cấp"
        },
        {   
            "input_text":"Toi quân tam toi san phẩm dden năng luowng mawt trowi  và thiết bj Wifi có giá tiết kiệm",
            "command":"Tôi quan tâm tới sản phẩm đèn năng lượng mặt trời và Thiết bị Wifi có giá tiết kiệm",
            "object": ["đèn năng lượng mặt trời", "Thiết bị Wifi"],
            "power":"",           
            "value":"",
            "weight":"",
            "volume":"",
            "intent":"tiết kiệm"
        },
        {   
            "input_text":"toi muon mua toi san pham dieu hoa có cong suat trên 500W",
            "command":"Tôi muốn mua điều hòa có công suất trên 500W",
            "object": ["điều hòa"],
            "power":"trên 500W",           
            "value":"",
            "weight":"",
            "volume":"",
            "intent":""
        },
        {
            "input_text":"Toi quan tam tới sp bình nuowc nongs gia re",
            "command":"Tôi quan tâm tới sản phẩm bình nước nóng giá rẻ",
            "object": ["điều hòa"],
            "power":"",           
            "value":"",
            "weight":"",
            "volume":"",
            "intent":"rẻ"
        },
        {
            "input_text":"cho toi may giatt có kho luong 13kg",
            "command":"cho tôi máy giặt có khối lượng 13kg",
            "object": ["máy giặt"],
            "power":"",           
            "value":"",
            "weight":"13kg",
            "volume":"",
            "intent":""
        },
        {
            "input_text":"Cho toi biunh nước nong có dung tích 30 lít",
            "command":"cho tôi bình nước nóng có dung tích 30 lít",
            "object": ["bình nước nóng"],
            "power":"",           
            "value":"",
            "weight":"",
            "volume":"30 lít",
            "intent":""
        },
        {
            "input_text":"binh dun nuoc lam bang chat lieu gi",
            "command":"bình đun nước làm bằng chất liệu gì",
            "object": ["bình đun nước"],
            "power":"",           
            "value":"",
            "weight":"",
            "volume":"",
            "intent":"chất liệu"
        },
        {
            "input_text":"ben bạn co thiete bị cam giá trên 10 triêju",
            "command":"bên bạn có thiết bị Camera giá trên 10 triệu",
            "object": ["điều hòa"],
            "power":"",           
            "value":["trên 10 triệu"],
            "weight":"",
            "volume":"",
            "intent":""
        },
        {
            "input_text":"Đèn NĂNG luong măt troi",
            "command":"đèn năng lượng mặt trời",
            "object":["đèn năng lượng mặt trời"],
            "power":"",           
            "value":"",
            "weight":"",
            "volume":"",
            "intent":""
        },
         {
            "input_text":"SOluong san pham diều hoa 2 chieu",
            "command": "Số lượng sản phẩm điều hòa 2 chiều",
            "object": ["điều hòa"],
            "power":"",           
            "value":"",
            "weight":"",
            "volume":"",
            "intent":"2 chiều"
        },
        {
            "input_text":"San pham bep tu nao ban re nhat",
            "command":"Sản phẩm bếp từ nào bán rẻ nhất",
            "object":["bếp từ"],
            "power":"",           
            "value":"",
            "weight":"",
            "volume":"",
            "intent":"bán rẻ nhất"
        },
        {
            "input_text":"Bep tu nao có cog suat lon nhất",
            "command":"Bếp từ nào có công suất lớn nhất",
            "object":["bếp từ"],
            "power":"",           
            "value":"",
            "weight":"",
            "volume":"",
            "intent":"công suất lớn nhất"
        },
        {
            "input_text":"so sánh DIEU HOA đai kin và điều ha LG tầm giá 10tr",
            "command":"so sánh điều hòa daikin và điều hòa LG tầm giá 10tr",
            "object":["điều hòa daikin","điều hòa LG"],
            "power":"",           
            "value":["10tr"],
            "weight":"",
            "volume":"",
            "intent":""
        },
        {
            "input_text":"ghe massage dai ki o san có công suất lứn nhất",
            "command":"ghế massage daikiosan nào có công suất lớn",
            "object":["ghế massage daikiosan"],
            "power":"",           
            "value":"",
            "weight":"",
            "volume":"",
            "intent":"công suất lớn"
        },
        {
            "input_text":"may saay co gia duoi 10 trieu",
            "command":"máy sấy có giá dưới 10 triệu",
            "object":["máy sấy"],
            "power":"",           
            "value":["dưới 10 triệu"],
            "weight":"",
            "volume":"",
            "intent":""
        },
        {
            "input_text":"maay giatt a qua 9 kg AQW-F91GT.S là lồng ngang hay lồng đứng",
            "command":"Máy Giặt Aqua 9 Kg AQW-F91GT.S là lồng ngang hay lồng đứng",
            "object":["Máy Giặt Aqua 9 Kg AQW-F91GT.S"],
            "power":"",           
            "value":"",
            "weight":"",
            "volume":"",
            "intent":"lồng ngang hay lồng đứng"
        },
        {
            "input_text":"Toii muons mua  mays giat lòng ngang",
            "command":"tôi muốn mua máy giặt lồng ngang",
            "object":["Máy Giặt"],
            "power":"",           
            "value":"",
            "weight":"",
            "volume":"",
            "intent":"lồng ngang"
        },
        {
            "input_text":"May loc nuoc KaroFI KAQ-U06V và may loc nuoc Empire Nóng Nguội - 10 cấp lọc EPML038 cái nào tốt hơn? ",
            "command":"Máy lọc nước Karofi KAQ-U06V và Máy lọc nước Empire Nóng Nguội - 10 cấp lọc EPML038 cái nào tốt hơn?",
            "object":["Máy lọc nước Karofi KAQ-U06V", "Máy lọc nước Empire Nóng Nguội - 10 cấp lọc EPML038"],
            "power":"",           
            "value":"",
            "weight":"",
            "volume":"",
            "intent":""
        },
        {
            "input_text":"Thoi gian su dug trng BÌNH cùa ghe massage dai ki o san là bao lau",
            "command": "Thời gian sử dụng trung bình của ghế massage daikiosan là bao lâu?",
            "object": ["Ghế massage daikiosan"],
            "power":"",           
            "value":"",
            "weight":"",
            "volume":"",
            "intent":"Thời gian sử dụng"
        },
        {
            "input_text":" Kisch thước mọt số sna pham DDIeu hòa",
            "command": "Kích thước một số sản phẩm điều hòa",
            "object": ["điều hòa"],
            "power":"",           
            "value":"",
            "weight":"",
            "volume":"",
            "intent":"Kích thước"
        },
        {
            "input_text":"Diện tích chiếu sáng den nawg luongj măt troi",
            "command": "Diện tích chiếu sáng đèn năng lượng mặt trời",
            "object": ["đèn năng lượng mặt trời"],
            "power":"",           
            "value":"",
            "weight":"",    
            "volume":"",
            "intent":"Diện tích chiếu sáng"
        },
        {
            "input_text":"Diện tích chiếu sáng den nawg LUONg măt troi công suất :90W",
            "command": "Diện tích chiếu sáng đèn năng lượng mặt trời công suất 90W",
            "intent":"Diện tích chiếu sáng",
            "object": ["đèn năng lượng mặt trời"],
            "power":"90W",           
            "value":"",
            "weight":"",
            "volume":""
        },
            
        {
            "input_text":"San pham BANLA nao 5lit",
            "command":"Sản phẩm bàn là nào 5 lít",
            "object":["bàn là"],
            "power":"",           
            "value":"",
            "weight":"",
            "volume":"5 lít",
            "intent":""
        },
        {
            "input_text":"Bep TU nao có cog suat lon nhất",
            "command":"Bếp từ nào có công suất lớn nhất",
            "object":["bếp từ"],
            "power":"",           
            "value":"",
            "weight":"",
            "volume":"",
            "intent":"công suất lớn"
        },
        {
            "input_text":"so sánh DIEU HOA đai kin và điều hÒa LG",
            "command":"so sánh điều hòa daikin và điều hòa LG",
            "object":["điều hòa daikin","điều hòa LG"],
            "power":"",           
            "value":"",
            "weight":"",
            "volume":"",
            "intent":"so sánh"
        },
        {
            "input_text":"binh sun nuoc có giar khooang 5tr",
            "command":"Cho tôi bình đun nước có giá khoảng 5tr",
            "object":["bình đun nước"],
            "power":"",           
            "value":["khoảng 5tr"],
            "weight":"",
            "volume":"",
            "intent":""
        },
        {
            "input_text":"Tôi quan tâm tới sản phẩm đieu hoa giá 10tr",
            "command":"Tôi muốn mua thiết bị Webcam dưới 10 triệu và đèn năng lượng mặt trời trên 8 triệu",
            "object":["thiết bị Webcam", "đèn năng lượng mặt trời"],
            "power":"",           
            "value":["10tr", "trên 8 triệu"],
            "weight":"",
            "volume":"",
            "intent":""
        }
        ]

yolo_params:
  weight_path: "weight/weight_26_100ep.pt"
  conf_thres: 0.3
  classes: {
            0: 'Bàn chải điện',
            1: 'Bàn là',
            2: 'Bếp từ',
            3: 'Bình đun nước',
            4: 'Bình nóng lạnh',
            5: 'Đèn năng lượng mặt trời',
            6: 'Điều hòa',
            7: 'Ghế massage Daikiosan',
            8: 'Lò vi sóng',
            9: 'Máy cạo râu',
            10: 'Máy đánh trứng',
            11: 'Máy ép',
            12: 'Máy giặt',
            13: 'Máy hút bụi',
            14: 'Máy lọc không khí',
            15: 'Máy lọc nước',
            16: 'Máy sấy tóc',
            17: 'Máy xay',
            18: 'Nồi áp suất',
            19: 'Nồi chiên không dầu',
            20: 'Nồi cơm điện',
            21: 'Robot hút bụi',
            22: 'Thiết bị Webcam',
            23: 'Thiết bị Wifi',
            24: 'Thiết bị camera',
            25: 'Lò nướng'
        }