server:
  ip_address: "0.0.0.0"
  port: "8099"
  saved_data_path: "result"
parameter:
  embeddings_name: "sentence-transformers/all-MiniLM-L6-v2"

  DATA_PATH: "data/"
  DB_FAISS_PATH: "ChatBot_Extract_Intent/vectorstore/db_faiss"
  DB_MESSAGES: "ChatBot_Extract_Intent/db_messages/"

  # Số đoạn sẽ được thêm vào lời nhắc. Quá nhiều đoạn trích và bạn có nguy cơ bị cả lời nhắc vượt qua
  # giới hạn mã thông báo và mô hình không thể tìm thấy câu trả lời chính xác
  prompt_number_snippets: 5

  # GPT related constants
  gpt_model_to_use: "gpt-3.5-turbo-16k"

  temperature: 0
  gpt_max_tokens: 256

  # Số tin nhắn của người dùng trước đây sẽ được sử dụng để tìm kiếm các đoạn có liên quan
  search_number_messages: 3

  # PDF Chunking constants
  chunk_size: 128
  chunk_overlap: 24

  # Số đoạn trích được FAISS truy xuất
  number_snippets_to_retrieve: 5
  
  #Thông tin sản phẩm
  data_private: ./ChatBot_Extract_Intent/data/product_final_204_oke.xlsx

  num_product: 3  # Số lượng sản phẩm tối đa cần tìm

  
  #
  raw_answer: ["Mình là trợ lý AI của VCC. Mình được tạo ra để hỗ trợ và giải đáp về các sản phẩm của VCC, hiện tại mình vẫn đang trong quá trình phát triển nên không phải lúc nào cũng đúng. Bạn có thể phản hồi để giúp mình cải thiện tốt hơn.",
                "Mình là trợ lý AI của VCC. Mình được tạo ra để hỗ trợ và giải đáp về các sản phẩm của VCC như: Thông tin sản phẩm, giá tiền, số lượng, thông số sản phẩm, . . . Hãy hỏi mĩnh những thông tin này để mình giúp đỡ."]
  
  can_not_res: ['Rất tiếc về điều này. Tôi vẫn đang trong quá trình học và cải thiện, nên không thể giúp bạn với câu hỏi này vào lúc này. Hãy đặt câu hỏi khác để tôi có thể hỗ trợ bạn tốt hơn!',
                'Xin lỗi về sự bất tiện này. Tôi đang cố gắng nâng cao khả năng của mình mỗi ngày, nhưng hiện tại vẫn chưa đủ để xử lý câu hỏi này. Mong bạn thông cảm và tiếp tục hỏi câu hỏi khác nếu cần!',
                'Xin lỗi về sự phiền toái này. Tôi đang trong quá trình học hỏi và cải thiện từng ngày, nhưng vẫn chưa đủ để giải quyết câu hỏi của bạn. Hãy để tôi biết nếu có bất kỳ điều gì khác mà bạn cần giúp đỡ!',
                'Xin lỗi về sự bất tiện này. Hiện tại, tôi vẫn đang trong quá trình học và cải thiện, nên chưa thể giúp bạn với câu hỏi này. Tuy nhiên, tôi rất sẵn lòng hỗ trợ bạn với bất kỳ câu hỏi nào khác bạn có. Hãy đặt câu hỏi khác để tôi có thể giúp bạn tốt hơn!',
                'Xin lỗi, hiện tại tôi vẫn đang trong quá trình học và cải thiện, nên chưa thể giúp bạn với câu hỏi này. Tuy nhiên, tôi rất sẵn lòng hỗ trợ bạn với bất kỳ câu hỏi nào khác bạn có. Hãy đặt câu hỏi khác để tôi có thể giúp bạn tốt hơn!']

    

  example_input: [
        {
            "command":"Tôi quan tâm tới sản phẩm điều hòa và Thiết bị Wifi",
            "demand":"quan tâm",
            "object": ["điều hòa", "Thiết bị Wifi"],
            "value":"",
        },
        {
            "command":"Tôi quan tâm tới sản phẩm điều hòa, máy giặt",
            "demand":"quan tâm",
            "object": ["điều hòa","máy giặt"],
            "value":"",
        },
        {
            "command":"Tôi quan tâm máy giặt lồng ngang",
            "demand":"quan tâm",
            "object": ["máy giặt"],
            "value":"lồng ngang",
        },
        {
            "command":"Tôi quan tâm tới sản phẩm điều hòa giá trên 10 triệu",
            "demand":"giá",
            "object": ["điều hòa"],
            "value":"trên 10 triệu",
        },
        {
            "command":"số lượng sản phẩm đèn năng lượng mặt trời",
            "demand":"số lượng",
            "object":["đèn năng lượng mặt trời"],
            "value":"",
        },
         {
            "command": "Số lượng sản phẩm điều hòa 2 chiều",
            "demand": "Số lượng",
            "object": ["điều hòa"],
            "value": "2 chiều"
        },
        {
            "command": "có bao nhiêu điều hòa 2 chiều",
            "demand": "bao nhiêu",
            "object": ["điều hòa"],
            "value": "2 chiều"
        },
        {
            "command":"Sản phẩm bếp từ nào bán chạy nhất",
            "demand":"bán",
            "object":["bếp từ"],
            "value":"chạy nhất",
        },
        {
            "command":"Sản phẩm bán chạy nhất là sản phẩm nào?",
            "demand":"bán",
            "object":[],
            "value":"chạy nhất",

        },
        {
            "command":"Bếp từ nào có công suất lớn nhất",
            "demand":"công suất",
            "object":["bếp từ"],
            "value":"lớn nhất",
        },
        {
            "command":"xin chào",
            "demand":"",
            "object":[],
            "value":"",
        },
        {
            "command":"so sánh điều hòa daikin và điều hòa LG tầm giá 10tr",
            "demand":"so sánh",
            "object":["điều hòa daikin","điều hòa LG"],
            "value":"10tr",
        },
        {
            "command":"bình đun nước có công suất trên 1000w",
            "demand":"công suất",
            "object":["bình đun nước"],
            "value":"trên 1000w",
        },
        {
            "command":"máy giặt có giá dưới 10 triệu",
            "demand":"giá",
            "object":["máy giặt"],
            "value":"dưới 10,000,000",
        },
        {
            "command":"Máy Giặt Aqua 9 Kg AQW-F91GT.S là lồng ngang hay lồng đứng",
            "demand":"",
            "object":["Máy Giặt Aqua 9 Kg AQW-F91GT.S"],
            "value":"lồng ngang hay lồng đứng",
        },
        {
            "command":"tôi muốn mua máy giặt lồng ngang",
            "demand":"mua",
            "object":["Máy Giặt"],
            "value":"lồng ngang",
        },
        {
            "command":"Máy lọc nước Karofi KAQ-U06V và Máy lọc nước Empire Nóng Nguội - 10 cấp lọc EPML038 cái nào tốt hơn?",
            "demand":"tốt hơn",
            "object":["Máy lọc nước Karofi KAQ-U06V", "Máy lọc nước Empire Nóng Nguội - 10 cấp lọc EPML038"],
            "value":"",
        },
        {
            "command":"Quạt sưởi không khí AIO Smart bảo hành trong bao lâu?",
            "demand":"bảo hành",
            "object":["Quạt sưởi không khí AIO Smart"],
            "value":"",
        },
        {
            "command":"Quạt sưởi không khí AIO Smart bảo hành trong bao lâu?",
            "demand":"bảo hành",
            "object":["Quạt sưởi không khí AIO Smart"],
            "value":"",
        },
        {
            "command": "Loại máy giặt nào là phổ biến nhất hiện nay?",
            "demand": "",
            "object": ["máy giặt"],
            "value": "phổ biến nhất",
        },
        {
            "command": "máy giặt phổ biến nhất hiện nay là loại nào?",
            "demand": "",
            "object": ["máy giặt"],
            "value": "phổ biến nhất",
        },
        {
            "command": "Thời gian sử dụng trung bình của Ghế massage daikiosan là bao lâu?",
            "demand": "Thời gian sử dụng trung bình",
            "object": ["Ghế massage daikiosan"],
            "value": "",
        }
    ]

yolo_params:
  weight_path: "weight/weight_26_100ep.pt"
  conf_thres: 0.3
  classes: {
            0: 'Bàn chải điện',
            1: 'Bàn là',
            2: 'Bếp từ',
            3: 'Bình đun nước',
            4: 'Bình nóng lạnh',
            5: 'Đèn năng lượng mặt trời',
            6: 'Điều hòa',
            7: 'Ghế massage Daikiosan',
            8: 'Lò vi sóng',
            9: 'Máy cạo râu',
            10: 'Máy đánh trứng',
            11: 'Máy ép',
            12: 'Máy giặt',
            13: 'Máy hút bụi',
            14: 'Máy lọc không khí',
            15: 'Máy lọc nước',
            16: 'Máy sấy tóc',
            17: 'Máy xay',
            18: 'Nồi áp suất',
            19: 'Nồi chiên không dầu',
            20: 'Nồi cơm điện',
            21: 'Robot hút bụi',
            22: 'Thiết bị Webcam',
            23: 'Thiết bị Wifi',
            24: 'Thiết bị camera',
            25: 'Lò nướng'
        }
